#!/usr/bin/env python

LANGUAGE_MAP = [(["ab", "abkhaz"], "Abkhaz"),
                (["aa", "afar"], "Afar"),
                (["af", "afrikaans"], "Afrikaans"),
                (["ak", "akan"], "Akan"),
                (["sq", "albanian"], "Albanian"),
                (["am", "amharic"], "Amharic"),
                (["ar", "arabic"], "Arabic"),
                (["an", "aragonese"], "Aragonese"),
                (["hy", "armenian"], "Armenian"),
                (["as", "assamese"], "Assamese"),
                (["av", "avaric"], "Avaric"),
                (["ae", "avestan"], "Avestan"),
                (["ay", "aymara"], "Aymara"),
                (["az", "azerbaijani"], "Azerbaijani"),
                (["bm", "bambara"], "Bambara"),
                (["ba", "bashkir"], "Bashkir"),
                (["eu", "basque"], "Basque"),
                (["be", "belarusian"], "Belarusian"),
                (["bn", "bengali"], "Bengali"),
                (["bh", "bihari"], "Bihari"),
                (["bi", "bislama"], "Bislama"),
                (["bs", "bosnian"], "Bosnian"),
                (["br", "breton"], "Breton"),
                (["bg", "bulgarian"], "Bulgarian"),
                (["my", "burmese"], "Burmese"),
                (["ca", "catalan", "valencian"], "Catalan"),
                (["ch", "chamorro"], "Chamorro"),
                (["ce", "chechen"], "Chechen"),
                (["ny", "chichewa", "chewa", "nyanja"], "Chichewa"),
                (["zh", "chinese"], "Chinese"),
                (["cv", "chuvash"], "Chuvash"),
                (["kw", "cornish"], "Cornish"),
                (["co", "corsican"], "Corsican"),
                (["cr", "cree"], "Cree"),
                (["hr", "croatian"], "Croatian"),
                (["cs", "czech"], "Czech"),
                (["da", "danish"], "Danish"),
                (["dv", "divehi", "maldivian"], "Divehi"),
                (["nl", "dutch"], "Dutch"),
                (["dz", "dzongkha"], "Dzongkha"),
                (["en", "english"], "English"),
                (["eo", "esperanto"], "Esperanto"),
                (["et", "estonian"], "Estonian"),
                (["ee", "ewe"], "Ewe"),
                (["fo", "faroese"], "Faroese"),
                (["fj", "fijian"], "Fijian"),
                (["fi", "finnish"], "Finnish"),
                (["fr", "french"], "French"),
                (["ff", "fula"], "Fula"),
                (["gl", "galician"], "Galician"),
                (["ka", "georgian"], "Georgian"),
                (["de", "german"], "German"),
                (["el", "greek"], "Greek"),
                (["gn", "guarani"], "Guarani"),
                (["gu", "gujarati"], "Gujarati"),
                (["ht", "haitian"], "Haitian"),
                (["ha", "hausa"], "Hausa"),
                (["he", "hebrew"], "Hebrew"),
                (["hz", "herero"], "Herero"),
                (["hi", "hindi"], "Hindi"),
                (["ho", "hiri motu"], "Hiri Motu"),
                (["hu", "hungarian"], "Hungarian"),
                (["ia", "interlingua"], "Interlingua"),
                (["id", "indonesian"], "Indonesian"),
                (["ie", "interlingue"], "Interlingue"),
                (["ga", "irish"], "Irish"),
                (["ig", "igbo"], "Igbo"),
                (["ik", "inupiaq"], "Inupiaq"),
                (["io", "ido"], "Ido"),
                (["is", "icelandic"], "Icelandic"),
                (["it", "italian"], "Italian"),
                (["iu", "inuktitut"], "Inuktitut"),
                (["ja", "japanese"], "Japanese"),
                (["jv", "javanese"], "Javanese"),
                (["kl", "kalaallisut"], "Kalaallisut"),
                (["kn", "kannada"], "Kannada"),
                (["kr", "kanuri"], "Kanuri"),
                (["ks", "kashmiri"], "Kashmiri"),
                (["kk", "kazakh"], "Kazakh"),
                (["km", "khmer"], "Khmer"),
                (["ki", "kikuyu", "gikuyu"], "Kikuyu"),
                (["rw", "kinyarwanda"], "Kinyarwanda"),
                (["ky", "kirghiz", "kyrgyz"], "Kirghiz"),
                (["kv", "komi"], "Komi"),
                (["kg", "kongo"], "Kongo"),
                (["ko", "korean"], "Korean"),
                (["ku", "kurdish"], "Kurdish"),
                (["kj", "kwanyama", "kuanyama"], "Kwanyama"),
                (["la", "latin"], "Latin"),
                (["lb", "luxembourgish"], "Luxembourgish"),
                (["lg", "luganda"], "Luganda"),
                (["li", "limburgish"], "Limburgish"),
                (["ln", "lingala"], "Lingala"),
                (["lo", "lao"], "Lao"),
                (["lt", "lithuanian"], "Lithuanian"),
                (["lu", "luba-katanga"], "Luba-Katanga"),
                (["lv", "latvian"], "Latvian"),
                (["gv", "manx"], "Manx"),
                (["mk", "macedonian"], "Macedonian"),
                (["mg", "malagasy"], "Malagasy"),
                (["ms", "malay"], "Malay"),
                (["ml", "malayalam"], "Malayalam"),
                (["mt", "maltese"], "Maltese"),
                (["mi", "maori"], "Maori"),
                (["mr", "marathi"], "Marathi"),
                (["mh", "marshallese"], "Marshallese"),
                (["mn", "mongolian"], "Mongolian"),
                (["na", "nauru"], "Nauru"),
                (["nv", "navajo, navaho"], "Navajo, Navaho"),
                (["nb", "norwegian bokmal"], "Norwegian Bokmal"),
                (["nd", "north ndebele"], "North Ndebele"),
                (["ne", "nepali"], "Nepali"),
                (["ng", "ndonga"], "Ndonga"),
                (["nn", "norwegian nynorsk"], "Norwegian Nynorsk"),
                (["no", "nor", "norwegian"], "Norwegian"),
                (["ii", "nuosu"], "Nuosu"),
                (["nr", "south ndebele"], "South Ndebele"),
                (["oc", "occitan"], "Occitan"),
                (["oj", "ojibwe", "ojibwa"], "Ojibwe"),
                (["cu", "old church slavonic"], "Old Church Slavonic"),
                (["om", "oromo"], "Oromo"),
                (["or", "oriya"], "Oriya"),
                (["os", "ossetian", "ossetic"], "Ossetian"),
                (["pa", "panjabi", "punjabi"], "Panjabi"),
                (["pi", "pali"], "Pali"),
                (["fa", "persian"], "Persian"),
                (["pl", "polish"], "Polish"),
                (["ps", "pashto", "pushto"], "Pashto"),
                (["pt", "portuguese"], "Portuguese"),
                (["qu", "quechua"], "Quechua"),
                (["rm", "romansh"], "Romansh"),
                (["rn", "kirundi"], "Kirundi"),
                (["ro", "romanian"], "Romanian"),
                (["ru", "russian"], "Russian"),
                (["sa", "sanskrit"], "Sanskrit"),
                (["sc", "sardinian"], "Sardinian"),
                (["sd", "sindhi"], "Sindhi"),
                (["se", "northern sami"], "Northern Sami"),
                (["sm", "samoan"], "Samoan"),
                (["sg", "sango"], "Sango"),
                (["sr", "serbian"], "Serbian"),
                (["gd", "scottish gaelic"], "Scottish Gaelic"),
                (["sn", "shona"], "Shona"),
                (["si", "sinhala, sinhalese"], "Sinhala, Sinhalese"),
                (["sk", "slovak"], "Slovak"),
                (["sl", "slovene"], "Slovene"),
                (["so", "somali"], "Somali"),
                (["st", "southern sotho"], "Southern Sotho"),
                (["es", "spanish"], "Spanish"),
                (["su", "sundanese"], "Sundanese"),
                (["sw", "swahili"], "Swahili"),
                (["ss", "swati"], "Swati"),
                (["sv", "swedish"], "Swedish"),
                (["ta", "tamil"], "Tamil"),
                (["te", "telugu"], "Telugu"),
                (["tg", "tajik"], "Tajik"),
                (["th", "thai"], "Thai"),
                (["ti", "tigrinya"], "Tigrinya"),
                (["bo", "tibetan"], "Tibetan"),
                (["tk", "turkmen"], "Turkmen"),
                (["tl", "tagalog"], "Tagalog"),
                (["tn", "tswana"], "Tswana"),
                (["to", "tonga"], "Tonga"),
                (["tr", "turkish"], "Turkish"),
                (["ts", "tsonga"], "Tsonga"),
                (["tt", "tatar"], "Tatar"),
                (["tw", "twi"], "Twi"),
                (["ty", "tahitian"], "Tahitian"),
                (["ug", "uighur", "uyghur"], "Uighur"),
                (["uk", "ukrainian"], "Ukrainian"),
                (["ur", "urdu"], "Urdu"),
                (["uz", "uzbek"], "Uzbek"),
                (["ve", "venda"], "Venda"),
                (["vi", "vietnamese"], "Vietnamese"),
                (["vo", "volapuk"], "Volapuk"),
                (["wa", "walloon"], "Walloon"),
                (["cy", "welsh"], "Welsh"),
                (["wo", "wolof"], "Wolof"),
                (["fy", "frisian"], "Frisian"),
                (["xh", "xhosa"], "Xhosa"),
                (["yi", "yiddish"], "Yiddish"),
                (["yo", "yoruba"], "Yoruba"),
                (["za", "zhuang"], "Zhuang"),
                (["zu", "zulu"], "Zulu")]
